# Site settings
title: MaxKaye
email: m@xk.io
author: Max Kaye
description: "The personal site of Max Kaye"
baseurl: ""
url: "http://xk.io"
google_analytics: "UA-50153179-1"
animated: false
show_related_posts: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 20
paginate_path: "responses/page:num/"
sass:
  compressed: true

# Page settings
page.small: false

defaults: 
  -
    scope: 
      path: ""
      type: "posts"
    values: 
      response: false